# Generated by Django 6.0.2 on 2026-05-15 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(choices=[('subscription', 'اشتراك'), ('client', 'عميل'), ('plan', 'باقة'), ('user', 'مستخدم'), ('notification', 'تنبيه')], db_index=True, max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'أُنشئ'), ('updated', 'عُدِّل'), ('deleted', 'حُذف'), ('expired', 'انتهى'), ('renewed', 'جُدِّد'), ('cancelled', 'أُلغي')], db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='None لو العملية تلقائية من النظام', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org_id', 'created_at'], name='activity_lo_org_id_0601c7_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__5a4970_idx'), models.Index(fields=['org_id', 'entity_type', 'action'], name='activity_lo_org_id_bda562_idx')],
            },
        ),
    ]
