# Generated by Django 6.0.2 on 2026-05-16 15:44

import django.db.models.deletion
from django.db import migrations, models

def update_subscription_status(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionStatus = apps.get_model("subscriptions", "SubscriptionStatus")

    active_status, _ = SubscriptionStatus.objects.get_or_create(name="active" , is_default=True)
    pending_status, _ = SubscriptionStatus.objects.get_or_create(name="pending" , is_default=True)
    past_due_status, _ = SubscriptionStatus.objects.get_or_create(name="past_due" , is_default=True)
    trial_status, _ = SubscriptionStatus.objects.get_or_create(name="trial" , is_default=True)
    cancelled_status, _ = SubscriptionStatus.objects.get_or_create(name="cancelled" , is_default=True)

    status_mapping = {
        "active": active_status,
        "pending": pending_status,
        "past_due": past_due_status,
        "trial": trial_status,
        "cancelled": cancelled_status,
    }

    for subscription in Subscription.objects.all():
        if subscription.status in status_mapping:
            subscription.status = status_mapping[subscription.status]
            subscription.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_id'),
        ('subscriptions', '0004_alter_addon_id_alter_plan_id_alter_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_organiz_567789_idx',
            old_name='subscriptio_organiz_3cb096_idx',
        ),
        migrations.AddField(
            model_name='subscriptionstatus',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_statuses', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionstatus'),
        ),
        migrations.RunPython(update_subscription_status),
    ]
